### ISSUE TITLE
Cartoon World has no hosts

### ISSUE THREAD

**Issue by jimberkas** [HIGHWAY99/repository.thehighway#8]
Cartoon World was our most used add on for xbmc.  for the last week or so, I have zero hosts listed for each episode that we try to play.  I see Highway99 is still actively updating the add on.  I'm wondering if there is something I need to do in the configuration go get host files, or if this is a problem for everyone

**Comment by HIGHWAY99** [comment]
fixed this yesterday. try the new version on the repo.

**Comment by jimberkas** [comment]
I'll check it out first thing.  I tried v.0.1.9 last night.  then i rolled back to v.0.1.6 since that was the last known version to be working.  anyway, I'll check again tonight and let you know how it goes.
Thanks so much for responding!

**Comment by jimberkas** [comment]
still no hosts on v.0.1.9
am i missing something in the configurations?

**Comment by jimberkas** [comment]
ok, most shows are now working after installing and reinstalling and rebooting fire tv.  
i haven't checked them all of course, there are so many, but the first few I tried still had no hosts...
101 Dalmations, Aaah Real Monsters, Adventure Time, Aladdin are have no hosts.  Adventure Time is our most watched show, so thats a bummer.  
I'll keep trying different shows and see what works and what doesn't
doesn't seem to be an issue with the add-on, so thanks!
